# Generated by Django 5.1 on 2025-01-12 13:35

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Artist's name", max_length=100)),
                ('genre', models.CharField(help_text='Music genre of the artist', max_length=100)),
                ('photo', models.ImageField(blank=True, help_text='Photo of the artist', null=True, upload_to='artists/')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(default='Female', max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_permissions_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the album', max_length=100)),
                ('release_date', models.DateField(blank=True, help_text='Release date of the album', null=True)),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image of the album', null=True, upload_to='albums/')),
                ('artist', models.ForeignKey(help_text='Artist who created the album', on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='museic.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the song', max_length=100)),
                ('duration', models.DurationField(help_text='Duration of the song in HH:MM:SS format')),
                ('release_date', models.DateField(blank=True, help_text='Release date of the song', null=True)),
                ('file', models.FileField(blank=True, help_text='Audio file of the song', null=True, upload_to='songs/')),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image of the song', null=True, upload_to='songs/covers/')),
                ('album', models.ForeignKey(blank=True, help_text='Album where the song is included', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_songs', to='museic.album')),
                ('artist', models.ForeignKey(help_text='Artist who performed the song', on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='museic.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the playlist', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the playlist', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the playlist was created')),
                ('songs', models.ManyToManyField(help_text='Songs included in the playlist', related_name='playlists', to='museic.song')),
            ],
        ),
    ]
